from configs import DATE


create_master_template_table = f"""
CREATE TABLE IF NOT EXISTS `template_{DATE}` (
  `#` TEXT,
  `Scrape_Date` TEXT,
  `BU` VARCHAR(255) DEFAULT NULL,
  `SC` VARCHAR(255) DEFAULT NULL,
  `vertical` VARCHAR(255) DEFAULT NULL,
  `Seller id` TEXT,
  `analytic_super_category` TEXT,
  `Seller_Status` INT DEFAULT '1',
  `Combo_Status` TINYINT DEFAULT NULL,
  `Combo_Value` TEXT,
  `Category_by_FK_L1` TEXT,
  `Category_by_FK_L2` TEXT,
  `FK_FSN` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FK_BRAND` TEXT,
  `FK_Display_Price_incl_shipping` TEXT,
  `Product_Url_FK` TEXT,
  `Product_Url_MEESHO` TEXT,
  `Pincode` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `City` TEXT,
  `SKU_id_MEESHO` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SKU_id_FK` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Seller_Display_Name_MEESHO` TEXT,
  `Seller_Display_Name_FK` TEXT,
  `Product_title_MEESHO` TEXT,
  `Product_title_FK` TEXT,
  `Image_Url_MEESHO` TEXT,
  `Image_Url_FK` TEXT,
  `Count_of_Images_MEESHO` TEXT,
  `Count_of_Images_FK` TEXT,
  `Image_Count_Parity_with_reference_to_FK` TEXT,
  `Pixel_Size_of_the_Main_Image_MEESHO` TEXT,
  `Pixel_Size_of_the_Main_Image_FK` TEXT,
  `Discount_percent_MEESHO` TEXT,
  `Discount_percent_FK` TEXT,
  `MRP_MEESHO` TEXT,
  `MRP_FK` TEXT,
  `Price_Parity_by_MRP` TEXT,
  `Price_Parity_by_MRPpercent` TEXT,
  `Display_Price_On_PDP_Price_After_Discount_MEESHO` TEXT,
  `Display_Price_On_PDP_Price_After_Discount_FK` TEXT,
  `Display_Price_Parity_Price_After_Discount_with_reference_to_FK` TEXT,
  `Display_Price_Parity_percent_Price_After_Discount_with_reference` TEXT,
  `Price_in_Cart__After_Applying_Coupon_MEESHO` TEXT,
  `Price_in_Cart__After_Applying_Coupon_FK` TEXT,
  `Cart_Price_Parity_with_reference_to_FK__After_Applying_Coupon` TEXT,
  `Cart__Price_Delta_percent_FK` TEXT,
  `Weighted_Price_Delta_FK_Demand_Rate` TEXT,
  `Weighted_Price_Delta_MEESHO_Demand_Rate` TEXT,
  `Market_Demand_Rate` TEXT,
  `Price_Delta_percent_Market_Demand_Rate` TEXT,
  `Price_delta_by_Market_FK_&_MEESHO_demad_rate` TEXT,
  `In_Stock_Status_MEESHO` TEXT,
  `In_Stock_Status_MEESHO_Count` TEXT,
  `In_Stock_Status_FK` TEXT,
  `In_Stock_Status_FKCount` TEXT,
  `Delivery_Charges_MEESHO` TEXT,
  `Delivery_Charges_FK` TEXT,
  `Delivery_Charges_Parity` TEXT,
  `Product_Ratings_MEESHO` TEXT,
  `Product_Ratings_FK` TEXT,
  `Product_Ratings_Parity` TEXT,
  `Volume_of_Product_Rating_MEESHO` TEXT,
  `Volume_of_Product_Rating_FK` TEXT,
  `Seller_Rating_MEESHO` TEXT,
  `Seller_Rating_FK` TEXT,
  `Seller_Rating_Parity` TEXT,
  `MEESHO_Demand_Rate` TEXT,
  `Flipkart_Demand_Rate` TEXT,
  `Demand_Rate_Parity` TEXT,
  `Delivery_Date_MEESHO` TEXT,
  `Delivery_Date_FK` TEXT,
  `No_Delivery_Days_from_Scrape_Date_MEESHO` TEXT,
  `No_Delivery_Days_from_Scrape_Date_FK` TEXT,
  `Delivery_SLA_Parity_with_reference_to_FK` TEXT,
  `Delivery_SLA_Paritypercent_with_reference_to_FK` TEXT,
  `MEESHO_Demand_Rate_Delivery_SLA` TEXT,
  `Flipkart_Demand_Rate_Delivery_SLA` TEXT,
  `Market_Demand_Rate_Delivery_SLA` TEXT,
  `Weighted_Delivery_SLA_Delta_FK_Demand_Rate` TEXT,
  `Weighted_Delivery_SLA_Delta_MEESHO_Demand_Rate` TEXT,
  `SLA_Delta_percent_Market_Demand` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `SLA_Delta___Demand__Rate` TEXT,
  `Price_Range` TEXT,
  `Data_identifier` TEXT,
  `app_fw_flag` TEXT,
  `portfolio` TEXT,
  `product_id` TEXT,
  `supplier_id` TEXT,
  `sscat_id` TEXT,
  `sscat` TEXT,
  `input_image_url` TEXT,
  `fddww` TEXT,
  KEY `FK_FSN` (`FK_FSN`),
  KEY `Pincode` (`Pincode`),
  KEY `SKU_id_MEESHO` (`SKU_id_MEESHO`),
  KEY `SKU_id_FK` (`SKU_id_FK`),
  KEY `Pincode_2` (`Pincode`,`SKU_id_MEESHO`),
  KEY `Pincode_3` (`Pincode`,`SKU_id_FK`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
"""


create_vertical_master_template_table = f"""
CREATE TABLE IF NOT EXISTS`template_{DATE}` (
  `#` text,
  `Scrape_Date` text,
  `Seller_Status` int DEFAULT '1',
  `Vertical` text,
  `Vertical Understanding` text,
  `Gender` text,
  `Keywords` text,
  `position` text,
  `mtrusted` text,
  `Category_by_FK_L1` text,
  `Category_by_FK_L2` text,
  `FK_FSN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FK_BRAND` text,
  `FK_Display_Price_incl_shipping` text,
  `Product_Url_FK` text,
  `Product_Url_MEESHO` text,
  `Pincode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '560001',
  `City` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'BANGALORE',
  `SKU_id_MEESHO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SKU_id_FK` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Seller_Display_Name_MEESHO` text,
  `Seller_Display_Name_FK` text,
  `Product_title_MEESHO` text,
  `Product_title_FK` text,
  `Image_Url_MEESHO` text,
  `Image_Url_FK` text,
  `Count_of_Images_MEESHO` text,
  `Count_of_Images_FK` text,
  `Image_Count_Parity_with_reference_to_FK` text,
  `Pixel_Size_of_the_Main_Image_MEESHO` text,
  `Pixel_Size_of_the_Main_Image_FK` text,
  `Discount_percent_MEESHO` text,
  `Discount_percent_FK` text,
  `MRP_MEESHO` text,
  `MRP_FK` text,
  `Price_Parity_by_MRP` text,
  `Price_Parity_by_MRPpercent` text,
  `Display_Price_On_PDP_Price_After_Discount_MEESHO` text,
  `Display_Price_On_PDP_Price_After_Discount_FK` text,
  `Display_Price_Parity_Price_After_Discount_with_reference_to_FK` text,
  `Display_Price_Parity_percent_Price_After_Discount_with_reference` text,
  `Price_in_Cart__After_Applying_Coupon_MEESHO` text,
  `Price_in_Cart__After_Applying_Coupon_FK` text,
  `Cart_Price_Parity_with_reference_to_FK__After_Applying_Coupon` text,
  `Cart__Price_Delta_percent_FK` text,
  `Weighted_Price_Delta_FK_Demand_Rate` text,
  `Weighted_Price_Delta_MEESHO_Demand_Rate` text,
  `Market_Demand_Rate` text,
  `Price_Delta_percent_Market_Demand_Rate` text,
  `Price_delta_by_Market_FK_&_MEESHO_demad_rate` text,
  `In_Stock_Status_MEESHO` text,
  `In_Stock_Status_MEESHO_Count` text,
  `In_Stock_Status_FK` text,
  `In_Stock_Status_FKCount` text,
  `Delivery_Charges_MEESHO` text,
  `Delivery_Charges_FK` text,
  `Delivery_Charges_Parity` text,
  `Product_Ratings_MEESHO` text,
  `Product_Ratings_FK` text,
  `Product_Ratings_Parity` text,
  `Volume_of_Product_Rating_MEESHO` text,
  `Volume_of_Product_Rating_FK` text,
  `Seller_Rating_MEESHO` text,
  `Seller_Rating_FK` text,
  `Seller_Rating_Parity` text,
  `MEESHO_Demand_Rate` text,
  `Flipkart_Demand_Rate` text,
  `Demand_Rate_Parity` text,
  `Delivery_Date_MEESHO` text,
  `Delivery_Date_FK` text,
  `No_Delivery_Days_from_Scrape_Date_MEESHO` text,
  `No_Delivery_Days_from_Scrape_Date_FK` text,
  `Delivery_SLA_Parity_with_reference_to_FK` text,
  `Delivery_SLA_Paritypercent_with_reference_to_FK` text,
  `MEESHO_Demand_Rate_Delivery_SLA` text,
  `Flipkart_Demand_Rate_Delivery_SLA` text,
  `Market_Demand_Rate_Delivery_SLA` text,
  `Weighted_Delivery_SLA_Delta_FK_Demand_Rate` text,
  `Weighted_Delivery_SLA_Delta_MEESHO_Demand_Rate` text,
  `SLA_Delta_percent_Market_Demand` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `SLA_Delta___Demand__Rate` text,
  `product_description_meesho` longtext,
  `Price_Range` text,
  KEY `FK_FSN` (`FK_FSN`),
  KEY `Pincode` (`Pincode`),
  KEY `SKU_id_MEESHO` (`SKU_id_MEESHO`),
  KEY `SKU_id_FK` (`SKU_id_FK`),
  KEY `Pincode_2` (`Pincode`,`SKU_id_MEESHO`),
  KEY `Pincode_3` (`Pincode`,`SKU_id_FK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

"""


create_fk_meesho_mapping_template_table = f"""
    CREATE TABLE IF NOT EXISTS`template_{DATE}` (
      `#` TEXT,
      `Scrape_Date` TEXT,
      `BU` VARCHAR(255) DEFAULT NULL,
      `SC` VARCHAR(255) DEFAULT NULL,
      `vertical` VARCHAR(255) DEFAULT NULL,
      `Seller id` TEXT,
      `Analytic_super_category` TEXT,
      `app_fw_flag` TEXT,
      `Seller_Status` INT DEFAULT '1',
      `Combo_Status` TINYINT DEFAULT NULL,
      `Combo_Value` TEXT,
      `Category_by_FK_L1` TEXT,
      `Category_by_FK_L2` TEXT,
      `FK_FSN` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
      `FK_BRAND` TEXT,
      `FK_Display_Price_incl_shipping` TEXT,
      `Product_Url_FK` TEXT,
      `Product_Url_MEESHO` TEXT,
      `Pincode` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
      `City` TEXT,
      `SKU_id_MEESHO` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
      `SKU_id_FK` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
      `Seller_Display_Name_MEESHO` TEXT,
      `Seller_Display_Name_FK` TEXT,
      `Product_title_MEESHO` TEXT,
      `Product_title_FK` TEXT,
      `Image_Url_MEESHO` TEXT,
      `Image_Url_FK` TEXT,
      `Count_of_Images_MEESHO` TEXT,
      `Count_of_Images_FK` TEXT,
      `Image_Count_Parity_with_reference_to_FK` TEXT,
      `Pixel_Size_of_the_Main_Image_MEESHO` TEXT,
      `Pixel_Size_of_the_Main_Image_FK` TEXT,
      `Discount_percent_MEESHO` TEXT,
      `Discount_percent_FK` TEXT,
      `MRP_MEESHO` TEXT,
      `MRP_FK` TEXT,
      `Price_Parity_by_MRP` TEXT,
      `Price_Parity_by_MRPpercent` TEXT,
      `Display_Price_On_PDP_Price_After_Discount_MEESHO` TEXT,
      `Display_Price_On_PDP_Price_After_Discount_FK` TEXT,
      `Display_Price_Parity_Price_After_Discount_with_reference_to_FK` TEXT,
      `Display_Price_Parity_percent_Price_After_Discount_with_reference` TEXT,
      `Price_in_Cart__After_Applying_Coupon_MEESHO` TEXT,
      `Price_in_Cart__After_Applying_Coupon_FK` TEXT,
      `Cart_Price_Parity_with_reference_to_FK__After_Applying_Coupon` TEXT,
      `Cart__Price_Delta_percent_FK` TEXT,
      `Weighted_Price_Delta_FK_Demand_Rate` TEXT,
      `Weighted_Price_Delta_MEESHO_Demand_Rate` TEXT,
      `Market_Demand_Rate` TEXT,
      `Price_Delta_percent_Market_Demand_Rate` TEXT,
      `Price_delta_by_Market_FK_&_MEESHO_demad_rate` TEXT,
      `In_Stock_Status_MEESHO` TEXT,
      `In_Stock_Status_MEESHO_Count` TEXT,
      `In_Stock_Status_FK` TEXT,
      `In_Stock_Status_FKCount` TEXT,
      `Delivery_Charges_MEESHO` TEXT,
      `Delivery_Charges_FK` TEXT,
      `Delivery_Charges_Parity` TEXT,
      `Product_Ratings_MEESHO` TEXT,
      `Product_Ratings_FK` TEXT,
      `Product_Ratings_Parity` TEXT,
      `Volume_of_Product_Rating_MEESHO` TEXT,
      `Volume_of_Product_Rating_FK` TEXT,
      `Seller_Rating_MEESHO` TEXT,
      `Seller_Rating_FK` TEXT,
      `Seller_Rating_Parity` TEXT,
      `MEESHO_Demand_Rate` TEXT,
      `Flipkart_Demand_Rate` TEXT,
      `Demand_Rate_Parity` TEXT,
      `Delivery_Date_MEESHO` TEXT,
      `Delivery_Date_FK` TEXT,
      `No_Delivery_Days_from_Scrape_Date_MEESHO` TEXT,
      `No_Delivery_Days_from_Scrape_Date_FK` TEXT,
      `Delivery_SLA_Parity_with_reference_to_FK` TEXT,
      `Delivery_SLA_Paritypercent_with_reference_to_FK` TEXT,
      `MEESHO_Demand_Rate_Delivery_SLA` TEXT,
      `Flipkart_Demand_Rate_Delivery_SLA` TEXT,
      `Market_Demand_Rate_Delivery_SLA` TEXT,
      `Weighted_Delivery_SLA_Delta_FK_Demand_Rate` TEXT,
      `Weighted_Delivery_SLA_Delta_MEESHO_Demand_Rate` TEXT,
      `SLA_Delta_percent_Market_Demand` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
      `SLA_Delta___Demand__Rate` TEXT,
      `Price_Range` TEXT,
      KEY `FK_FSN` (`FK_FSN`),
      KEY `Pincode` (`Pincode`),
      KEY `SKU_id_MEESHO` (`SKU_id_MEESHO`),
      KEY `SKU_id_FK` (`SKU_id_FK`),
      KEY `Pincode_2` (`Pincode`,`SKU_id_MEESHO`),
      KEY `Pincode_3` (`Pincode`,`SKU_id_FK`)
    ) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    
    """


create_fk_link_table = f"""
CREATE TABLE IF NOT EXISTS `fk_product_links_{DATE}` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_url` VARCHAR(255) DEFAULT NULL,
  `status_560001` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'pending',
  PRIMARY KEY (`id`),
  UNIQUE KEY `fk_url` (`fk_url`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

"""


create_meesho_link_table = f"""
CREATE TABLE IF NOT EXISTS `product_links_{DATE}` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meesho_pid` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT 'pending',
  `status_560001` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'pending',
  PRIMARY KEY (`id`),
  UNIQUE KEY `meesho_pid` (`meesho_pid`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
"""


create_sy_meesho_template_table = f"""
CREATE TABLE IF NOT EXISTS `template_{DATE}` (
   `#` text,
  `Scrape_Date` text,
  `BU` varchar(255) DEFAULT NULL,
  `SC` varchar(255) DEFAULT NULL,
  `vertical` varchar(255) DEFAULT NULL,
  `Seller id` text,
  `analytic_super_category` text,
  `analytic_category` text,
  `Seller_Status` int DEFAULT '1',
  `Combo_Status` tinyint DEFAULT NULL,
  `Combo_Value` text,
  `Category_by_FK_L1` text,
  `Category_by_FK_L2` text,
  `FK_FSN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FK_BRAND` text,
  `FK_Display_Price_incl_shipping` text,
  `Product_Url_FK` text,
  `Product_Url_MEESHO` text,
  `Pincode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `City` text,
  `SKU_id_MEESHO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SKU_id_FK` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Seller_Display_Name_MEESHO` text,
  `Seller_Display_Name_FK` text,
  `Product_title_MEESHO` text,
  `Product_title_FK` text,
  `Image_Url_MEESHO` text,
  `Image_Url_FK` text,
  `Count_of_Images_MEESHO` text,
  `Count_of_Images_FK` text,
  `Image_Count_Parity_with_reference_to_FK` text,
  `Pixel_Size_of_the_Main_Image_MEESHO` text,
  `Pixel_Size_of_the_Main_Image_FK` text,
  `Discount_percent_MEESHO` text,
  `Discount_percent_FK` text,
  `MRP_MEESHO` text,
  `MRP_FK` text,
  `Price_Parity_by_MRP` text,
  `Price_Parity_by_MRPpercent` text,
  `Display_Price_On_PDP_Price_After_Discount_MEESHO` text,
  `Display_Price_On_PDP_Price_After_Discount_FK` text,
  `Display_Price_Parity_Price_After_Discount_with_reference_to_FK` text,
  `Display_Price_Parity_percent_Price_After_Discount_with_reference` text,
  `Price_in_Cart__After_Applying_Coupon_MEESHO` text,
  `Price_in_Cart__After_Applying_Coupon_FK` text,
  `Cart_Price_Parity_with_reference_to_FK__After_Applying_Coupon` text,
  `Cart__Price_Delta_percent_FK` text,
  `Weighted_Price_Delta_FK_Demand_Rate` text,
  `Weighted_Price_Delta_MEESHO_Demand_Rate` text,
  `Market_Demand_Rate` text,
  `Price_Delta_percent_Market_Demand_Rate` text,
  `Price_delta_by_Market_FK_&_MEESHO_demad_rate` text,
  `In_Stock_Status_MEESHO` text,
  `In_Stock_Status_MEESHO_Count` text,
  `In_Stock_Status_FK` text,
  `In_Stock_Status_FKCount` text,
  `Delivery_Charges_MEESHO` text,
  `Delivery_Charges_FK` text,
  `Delivery_Charges_Parity` text,
  `Product_Ratings_MEESHO` text,
  `Product_Ratings_FK` text,
  `Product_Ratings_Parity` text,
  `Volume_of_Product_Rating_MEESHO` text,
  `Volume_of_Product_Rating_FK` text,
  `Seller_Rating_MEESHO` text,
  `Seller_Rating_FK` text,
  `Seller_Rating_Parity` text,
  `MEESHO_Demand_Rate` text,
  `Flipkart_Demand_Rate` text,
  `Demand_Rate_Parity` text,
  `Delivery_Date_MEESHO` text,
  `Delivery_Date_FK` text,
  `No_Delivery_Days_from_Scrape_Date_MEESHO` text,
  `No_Delivery_Days_from_Scrape_Date_FK` text,
  `Delivery_SLA_Parity_with_reference_to_FK` text,
  `Delivery_SLA_Paritypercent_with_reference_to_FK` text,
  `MEESHO_Demand_Rate_Delivery_SLA` text,
  `Flipkart_Demand_Rate_Delivery_SLA` text,
  `Market_Demand_Rate_Delivery_SLA` text,
  `Weighted_Delivery_SLA_Delta_FK_Demand_Rate` text,
  `Weighted_Delivery_SLA_Delta_MEESHO_Demand_Rate` text,
  `SLA_Delta_percent_Market_Demand` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `SLA_Delta___Demand__Rate` text,
  `Price_Range` text,
  `mode_price` text,
  `median_price` text,
  `all_price` text,
  `all_variation` text,
  `moq` text,
  `unique_id` text,
  `coupon` text,
 `shopsy_exclusive` text,
  KEY `FK_FSN` (`FK_FSN`),
  KEY `Pincode` (`Pincode`),
  KEY `SKU_id_MEESHO` (`SKU_id_MEESHO`),
  KEY `SKU_id_FK` (`SKU_id_FK`),
  KEY `Pincode_2` (`Pincode`,`SKU_id_MEESHO`),
  KEY `Pincode_3` (`Pincode`,`SKU_id_FK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
"""


create_sy_link_table = f"""
    CREATE TABLE IF NOT EXISTS `sy_product_links_{DATE}` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `sy_url` VARCHAR(255) DEFAULT NULL,
      `status_212011` VARCHAR(255) DEFAULT 'pending',
      PRIMARY KEY (`id`),
      UNIQUE KEY `sy_url` (`sy_url`)
    ) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

    """


create_sy_meesho_link_table = f"""
    CREATE TABLE IF NOT EXISTS `product_links_{DATE}` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `meesho_pid` VARCHAR(255) DEFAULT NULL,
      `status` VARCHAR(255) DEFAULT 'pending',
      `status_212011` VARCHAR(255) DEFAULT 'pending',
      PRIMARY KEY (`id`),
      UNIQUE KEY `meesho_pid` (`meesho_pid`)
    ) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
    """
